services:
  backend:
    build: ./backend
    ports:
      - '8001:8001'
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./backend:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8001 --reload

  redis:
    image: redis:7
    ports:
      - '6379:6379'